### ISSUE TITLE
Super-image repo dead

### ISSUE THREAD

**Issue by JorisCod** [dzanaga/satio-pc#2]
I noticed the github repo for super-image:
https://github.com/eugenesiow/super-image

Is pretty dead, so it might be better to look for another package more recent and well-maintained for super-resolution.

In any case the super-image dependency is missing.

**Comment by dzanaga** [comment]
it should be an optional dependency. the super resolution part will need some better refactoring once we'll have time. we should train our own models or use some dedicated ones from partners. CESBIO is working on this. For the moment being, this does well.
